
# Контроллер по умолчанию, который будет вызываться из ноды.
default_controller: Texter:run
descr: Статические текстовые блоки.

# Установка дефолтных значений для контролеров, а также некоторая инфа о типе этих свойств.
defaults:
    editor:
        label: Редактор
        type: checkbox
        value: true
    text_item_id:
        label: ID текстового поля
        type: int
        value: 0
