services:
    texter:
        class: SmartCore\Bundle\TexterBundle\Twig\TexterExtension
        arguments:
            - @doctrine.orm.default_entity_manager
        tags:
            - { name: twig.extension }