parameters:
#    dmitxe_blog.example.class: Dmitxe\BlogBundle\Example

services:
#    dmitxe_blog.example:
#        class: %dmitxe_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
