parameters:
#    simpleblog_blog.example.class: SimpleBlog\BlogBundle\Example

services:
#    simpleblog_blog.example:
#        class: %simpleblog_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
