imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi: ~
    translator: { fallback: %locale% }
    secret: %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale: "%locale%"
    trusted_proxies: ~
    session: ~
    fragments: ~

# Twig Configuration
twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        html: @html
        pagerfanta_opts:
            previous_message: '&laquo;'
            next_message: '&raquo;'
            dots_message: ' … '

# Assetic Configuration
assetic:
    debug: %kernel.debug%
    use_controller: false
    bundles: [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        # jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        # jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver: %database_driver%
        host: %database_host%
        port: %database_port%
        dbname: %database_name%
        user: %database_user%
        password: %database_password%
        charset: UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path: %database_path%
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host: %mailer_host%
    username: %mailer_user%
    password: %mailer_password%
    spool: { type: memory }

knp_menu:
    twig:
        template: DmitxeSiteBundle:Menu:knp_menu.html.twig

mopa_bootstrap:
    form:
        error_type: block # or inline which is default
        render_required_asterisk: true
        render_optional_text: false

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Dmitxe\UserBundle\Entity\User
    group:
        group_class: Dmitxe\UserBundle\Entity\Group

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: '.tinymce'
    language: %locale%
    theme:
        simple:
            theme: 'modern'
            file_browser_callback : 'elFinderBrowser'
        advanced:
            file_browser_callback : 'elFinderBrowser'
            plugins:
                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
                 - "insertdatetime media nonbreaking save table contextmenu directionality"
                 - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic | fontselect fontsizeselect | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
            image_advtab: true

fm_elfinder:
    locale: %locale%
    editor: tinymce
    tinymce_popup_path: "asset[bundles/stfalcontinymce/vendor/tiny_mce/tiny_mce_popup.js]"
    showhidden: false # defaults to false
    fullscreen: true # defaults true, applies to simple and ckeditor editors
    connector:
        debug: false # defaults to false
        roots:       # at least one root must be defined
            uploads:
                driver: LocalFileSystem
                path: uploads
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                upload_deny: ['all']
                upload_max_size: 2M

vich_uploader:
    db_driver: orm
    mappings:
        blog_image:
            uri_prefix: /images/blog
            upload_destination: %kernel.root_dir%/../web/images/blog

smart_blog:
    article_class: Dmitxe\BlogBundle\Entity\Article
    tag_class: Dmitxe\BlogBundle\Entity\Tag

services:
    twig_extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags: [{ name: 'twig.extension' }]
