dmitxe_demo:
    resource: "@DmitxeDemoBundle/Resources/config/routing.yml"
    prefix:   /

smart_media:
    resource: "@SmartMediaBundle/Resources/config/routing.yml"
    prefix:   /

dmitxe_site:
    resource: "@DmitxeSiteBundle/Resources/config/routing.yml"
    prefix:   /

dmitxe_blog:
    resource: "@DmitxeBlogBundle/Resources/config/routing.yml"
    prefix:   /blog/

dmitxe_user:
    resource: "@DmitxeUserBundle/Resources/config/routing.yml"
    prefix:   /
