parameters:
#    simpleblog_site.example.class: SimpleBlog\SiteBundle\Example

services:
#    simpleblog_site.example:
#        class: %simpleblog_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

# Menu selected items
    simpleblog_site.menu.voter.request:
        class: SimpleBlog\SiteBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
