dmitxe_pages_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DmitxePagesBundle:Default:index }

dmitxe_pages_index:
    path: /admin/
    defaults: { _controller: SmartTexterBundle:Admin:index }

dmitxe_pages_create:
    path: /
    defaults: { _controller: SmartTexterBundle:Admin:create }

dmitxe_pages_update:
    path: /admin/{id}
    defaults: { _controller: SmartTexterBundle:Admin:update }
    requirements:
        id: \d+
