parameters:
#    dmitxe_pages.example.class: Pages\DmitxeBundle\Example

services:
#    dmitxe_pages.example:
#        class: %dmitxe_pages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
