parameters:
#    dmitxe_demo.example.class: Dmitxe\DemoBundle\Example

services:
#    dmitxe_demo.example:
#        class: %dmitxe_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
