parameters:
#    dmitxe_user.example.class: Dmitxe\UserBundle\Example

services:
#    dmitxe_user.example:
#        class: %dmitxe_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
